"""OHO 用户画像预设模板。

OHO 目标用户：25-44 岁 iPhone 用户，高频知识工作者。
核心人群：PM/创业者/管理层/研究者（高频会议推进型）、设计师/运营/记者/内容创作者（记录型知识工作者）。
次级：终身学习者（读书/摘录/课程笔记/思考碎片）。

按 target_api 动态加载：
    from interface_profiles import load_persona_presets
    templates = load_persona_presets('oho')
"""

import random

PERSONA_TEMPLATES = {
    "high_freq_meeting_pm": {
        "name": "高频会议PM",
        "description": "28-38岁，互联网/科技公司 PM，每天3-5个会，记录为了后续推进而非归档",
        "profile": {
            "age": lambda: random.choice(["29", "32", "35"]),
            "city": lambda: random.choice(["北京", "上海", "深圳", "杭州"]),
            "occupation": lambda: random.choice(["产品经理", "高级产品经理", "产品总监"]),
            "education": lambda: random.choice(["本科", "硕士"]),
            "relationship": lambda: random.choice(["单身", "有对象", "已婚"]),
            "personality": "外向驱动型，节奏快讨厌拖沓",
            "income_range": "25-50K/月",
            "spending_style": "工具型消费，效率优先",
            "devices": "iPhone + AirPods + MacBook",
            "usage_scenes": "开会、电话、通勤碎片、出差路上",
            "core_goal": "把会议要点和灵感低摩擦接住，后续可推进",
            "short_goal": "本周跟进行动项不丢失",
            "long_goal": "沉淀可复用的项目知识库",
            "pain_points": "会议录音难推进，要点散落各处，回看成本高",
            "constraints": "不愿为记录切 App，不愿做复杂整理",
            "risk_profile": "工具型，效率第一",
            "interests": "产品/项目管理/读书/咖啡",
            "language_style": "直接简洁，'记一下''跟进''推进'高频",
            "sample_dialog": "刚开完会，要点我整理一下",
            "info_sources": "同事/微信群/飞书/书籍",
            "decision_style": "快速决策，数据驱动",
            "relation_pace": "工具型，少寒暄",
            "scene_pref": "会议场景为主，通勤碎片为辅",
            "top_expectations": "低摩擦/可推进/可召回",
            "minefields": "强迫整理/信息丢失/语气拖沓",
            "pet_type": "",
            "pet_name": "",
            "pet_age": "",
            "pet_trait": "",
            "favorite_drink": lambda: random.choice(["美式", "拿铁", "手冲"]),
            "favorite_food": lambda: random.choice(["轻食", "日料", "快餐"]),
            "spicy_preference": lambda: random.choice(["微辣", "不辣"]),
            "current_hobby": lambda: random.choice(["读书", "健身", "投资"]),
            "learning": lambda: random.choice(["产品方法论", "英语", "管理学"]),
            "favorite_singer": "",
            "best_friend": lambda: random.choice(["老王", "老李", "老张"]),
            "stress_relief": lambda: random.choice(["跑步", "冥想", "喝咖啡"]),
            "work_time": "10:00-20:00",
            "lunch_habit": lambda: random.choice(["外卖", "食堂", "和同事出去吃"]),
            "commute": lambda: random.choice(["地铁", "网约车", "步行"]),
        },
        "facts": {
            ("work", "daily_schedule"): lambda: random.choice(["10-20点", "9-19点"]),
            ("work", "work_stress"): lambda: random.choice(["较高", "中等"]),
            ("preference", "favorite_drink"): lambda: random.choice(["美式", "拿铁"]),
        },
        "categories": ["work", "meeting", "project", "person", "task"],
    },
    "startup_founder": {
        "name": "创业者",
        "description": "30-42岁，初创公司创始人，电话/会议/决策密集，记录驱动决策",
        "profile": {
            "age": lambda: random.choice(["31", "35", "38", "40"]),
            "city": lambda: random.choice(["北京", "上海", "深圳"]),
            "occupation": lambda: random.choice(["创始人", "联合创始人", "CEO"]),
            "education": lambda: random.choice(["硕士", "MBA", "博士"]),
            "relationship": lambda: random.choice(["已婚", "有对象"]),
            "personality": "目标导向，节奏极快，决策果断",
            "income_range": "50K+/月",
            "spending_style": "投资型消费，时间最贵",
            "devices": "iPhone + iPad + MacBook",
            "usage_scenes": "电话/路演/董事会/投资人沟通",
            "core_goal": "决策依据不丢失，关键判断可追溯",
            "short_goal": "本周关键决策会议要点沉淀",
            "long_goal": "公司决策档案与复盘素材",
            "pain_points": "电话结论散落，复盘缺素材",
            "constraints": "0 摩擦，不能为记录多花一秒",
            "risk_profile": "高风险高回报",
            "interests": "商业/投资/管理/读书",
            "language_style": "极简，结论先行",
            "sample_dialog": "刚和投资人通完电话，结论记一下",
            "info_sources": "投资人/同行/书籍/播客",
            "decision_style": "直觉+数据，快速验证",
            "relation_pace": "极简，无寒暄",
            "scene_pref": "电话/路演/董事会议",
            "top_expectations": "低摩擦/可追溯/不丢关键判断",
            "minefields": "强迫整理/复述无提炼/信息丢失",
            "pet_type": "",
            "pet_name": "",
            "pet_age": "",
            "pet_trait": "",
            "favorite_drink": lambda: random.choice(["美式", "黑咖啡", "气泡水"]),
            "favorite_food": lambda: random.choice(["简餐", "商务午餐"]),
            "spicy_preference": "不辣",
            "current_hobby": lambda: random.choice(["跑步", "高尔夫", "读书"]),
            "learning": lambda: random.choice(["管理学", "财务", "战略"]),
            "favorite_singer": "",
            "best_friend": lambda: random.choice(["合伙人", "老同学"]),
            "stress_relief": lambda: random.choice(["运动", "独处", "阅读"]),
            "work_time": "全天候",
            "lunch_habit": "商务午餐",
            "commute": "专车",
        },
        "facts": {
            ("work", "work_stress"): "极高",
            ("work", "colleague_relation"): "合伙人关系",
        },
        "categories": ["work", "meeting", "call", "project", "person"],
    },
    "designer_creator": {
        "name": "设计师/创作者",
        "description": "25-35岁，设计师/运营/记者/内容创作者，输入碎片多，灵感频繁",
        "profile": {
            "age": lambda: random.choice(["26", "28", "31", "33"]),
            "city": lambda: random.choice(["上海", "北京", "杭州", "成都"]),
            "occupation": lambda: random.choice(["设计师", "内容运营", "记者", "自由创作者"]),
            "education": lambda: random.choice(["本科", "硕士"]),
            "relationship": lambda: random.choice(["单身", "有对象"]),
            "personality": "敏感型，审美驱动，灵感驱动",
            "income_range": "15-30K/月",
            "spending_style": "审美型消费，颜值正义",
            "devices": "iPhone + iPad + 相机",
            "usage_scenes": "看展/逛街/通勤/咖啡店",
            "core_goal": "灵感不丢失，可串联成素材池",
            "short_goal": "本周灵感可成文",
            "long_goal": "个人作品集与素材库",
            "pain_points": "灵感来得快走得快，记录路径太慢",
            "constraints": "记录要快，不能切 App",
            "risk_profile": "审美型，体验驱动",
            "interests": "设计/艺术/读书/咖啡/旅行",
            "language_style": "感性但有质感，细节描述多",
            "sample_dialog": "刚看到个海报配色绝了，记一下",
            "info_sources": "小红书/Behance/展览/书籍",
            "decision_style": "直觉驱动",
            "relation_pace": "少寒暄，重质感",
            "scene_pref": "灵感碎片场景",
            "top_expectations": "低摩擦/保留原始语气/可串联",
            "minefields": "强迫结构化/丢失语气/复述无质感",
            "pet_type": "",
            "pet_name": "",
            "pet_age": "",
            "pet_trait": "",
            "favorite_drink": lambda: random.choice(["手冲", "拿铁", "茶"]),
            "favorite_food": lambda: random.choice(["轻食", "甜品", "日料"]),
            "spicy_preference": lambda: random.choice(["微辣", "不辣"]),
            "current_hobby": lambda: random.choice(["看展", "摄影", "读书"]),
            "learning": lambda: random.choice(["设计", "艺术史", "写作"]),
            "favorite_singer": "",
            "best_friend": lambda: random.choice(["同行", "闺蜜"]),
            "stress_relief": lambda: random.choice(["看展", "散步", "听音乐"]),
            "work_time": "弹性",
            "lunch_habit": "外出觅食",
            "commute": "步行/地铁",
        },
        "facts": {
            ("preference", "weekend_activity"): lambda: random.choice(["看展", "逛咖啡店", "摄影"]),
            ("hobby", "favorite_movie"): lambda: random.choice(["文艺片", "纪录片"]),
        },
        "categories": ["spark", "note", "hobby", "preference", "place"],
    },
    "researcher_writer": {
        "name": "研究者/写作者",
        "description": "28-40岁，研究者/终身学习者/写作者，读书摘录/课程笔记/思考碎片密集",
        "profile": {
            "age": lambda: random.choice(["29", "33", "36", "40"]),
            "city": lambda: random.choice(["北京", "上海", "南京", "武汉"]),
            "occupation": lambda: random.choice(["研究员", "高校教师", "作家", "终身学习者"]),
            "education": lambda: random.choice(["博士", "硕士"]),
            "relationship": lambda: random.choice(["已婚", "单身"]),
            "personality": "思考型，逻辑驱动，深度优先",
            "income_range": "20-40K/月",
            "spending_style": "知识型消费，书籍课程优先",
            "devices": "iPhone + Kindle + MacBook",
            "usage_scenes": "读书/听课/思考/写作",
            "core_goal": "思考碎片可串联成长期输出",
            "short_goal": "本月读书笔记可成文",
            "long_goal": "个人知识库与作品",
            "pain_points": "读书摘录散落，思考无法串联",
            "constraints": "记录要快，不打断阅读心流",
            "risk_profile": "保守型，深度优先",
            "interests": "读书/写作/思考/课程",
            "language_style": "理性，逻辑清晰",
            "sample_dialog": "刚读到一段话特别有启发，记一下",
            "info_sources": "书籍/课程/论文/播客",
            "decision_style": "论证驱动",
            "relation_pace": "少寒暄，重逻辑",
            "scene_pref": "读书思考场景",
            "top_expectations": "低摩擦/可串联/可检索",
            "minefields": "强迫结构化/丢失原始语气/无法检索",
            "pet_type": "",
            "pet_name": "",
            "pet_age": "",
            "pet_trait": "",
            "favorite_drink": lambda: random.choice(["茶", "黑咖啡", "白开水"]),
            "favorite_food": "简餐",
            "spicy_preference": "不辣",
            "current_hobby": lambda: random.choice(["读书", "写作", "思考"]),
            "learning": lambda: random.choice(["哲学", "历史", "心理学"]),
            "favorite_singer": "",
            "best_friend": lambda: random.choice(["同行", "书友"]),
            "stress_relief": lambda: random.choice(["散步", "冥想", "阅读"]),
            "work_time": "弹性",
            "lunch_habit": "简餐",
            "commute": "步行",
        },
        "facts": {
            ("hobby", "favorite_movie"): lambda: random.choice(["纪录片", "文艺片"]),
            ("preference", "weekend_activity"): lambda: random.choice(["读书", "逛书店", "听课"]),
        },
        "categories": ["note", "spark", "hobby", "preference", "project"],
    },
}
